version: '3.8'

networks:
  moonnight-blog-network:
    driver: bridge

volumes:
  moonnight-blog-data:
    driver: local

services:
  moonnight-blog-backend:
    container_name: moonnight-blog-backend
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - /var/www/moonnight-blog/vendor
      - /var/www/moonnight-blog/node_modules
      - ./:/var/www/moonnight-blog
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    stdin_open: true
    tty: true
    networks:
      - moonnight-blog-network

  moonnight-blog-db:
    container_name: moonnight-blog-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
        - "5432:5432"
    networks:
      - moonnight-blog-network

  moonnight-blog-nginx:
    container_name: moonnight-blog-nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/moonnight-blog
      - ./.docker/nginx/conf/:/etc/nginx/conf.d/
      - ./.docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - moonnight-blog-network
